RGBLIGHT_ENABLE    = no
RGB_MATRIX_ENABLE  = yes
MOUSEKEY_ENABLE    = yes
NKRO_ENABLE        = yes
OLED_DRIVER_ENABLE = yes
COMMAND_ENABLE     = no
UNICODE_ENABLE     = yes
EXTRAFLAGS        += -flto
